touch areaofcircle.txt
touch calculator.txt
touch greatestThreenum.txt
touch compilemeanSD.txt
touch reversenum.txt
touch primeNumUptogivenlimit.txt
touch fibonacci.txt
touch armstrong.txt
touch reversepalindrom.txt
touch factorial.txt
touch evenOrOdd.txt
touch employee.txt
touch displaygoodmorning.txt
touch countLineword.txt
touch sumofAlldigit.txt
